version: '3'

services:
  haproxy:
    build:
      context: ./haproxy
      dockerfile: haproxy.yaml
    volumes:
      - ./haproxy:/usr/local/etc/haproxy:ro
      - ./certs:/etc/certs:ro
    ports:
      - "80:80"
      - "443:443"

  nginx_ha:
    build:
      context: ./nginx_ha
      dockerfile: nginx_file.yaml

  nginx_ha2:
    build:
      context: ./nginx_ha2
      dockerfile: nginx_file.yaml

